/**
 * 260909_1: 入力待ちのセッションが「切断」へ誤って倒れる問題。
 *
 * 2026-09-09 実測（instagram-app）: 入力待ち通知で確認待ち → ユーザーが /effort /model（ローカルコマンド）を打つ →
 * transcript が動いたので「許可後に transcript が更新」として実行中へ復帰 → 終端分類がローカルコマンドの user レコードを
 * 「open」と読むため終了検知が効かず → 15 分後に「切断」（登録簿は idle・プロセス生存）。
 * 対策: (1) 終端分類でローカルコマンドの痕跡を読み飛ばす (2) 確認待ちからの transcript 復帰は終端 open のときだけ
 * (3) 登録簿 idle のまま transcript が止まった実行中は「完了」へ（切断ではない）(4) 切断検知は登録簿 idle を対象外にする
 */
import { describe, expect, it } from "vitest";
import {
  TRANSCRIPT_STALE_HARD_MS,
  TRANSCRIPT_STALE_MS,
  CONFIRM_RESUME_MARGIN_MS,
  CONFIRM_RESUME_MIN_AGE_MS,
  findDisconnected,
  findIdleConcluded,
  findResumedFromConfirm,
  type ConfirmTarget,
  type SweepTarget,
} from "../src/main/liveness-monitor";
import { classifyTurnEnd } from "../src/main/session-scan";

const T0 = 1_000_000;
const user = (content: string): Record<string, unknown> => ({ type: "user", message: { role: "user", content } });
const assistant = (): Record<string, unknown> => ({ type: "assistant", message: { role: "assistant", content: [{ type: "text", text: "done" }] } });
const summary = (): Record<string, unknown> => ({ type: "system", subtype: "stop_hook_summary", preventedContinuation: false });
const duration = (): Record<string, unknown> => ({ type: "system", subtype: "turn_duration" });

describe("classifyTurnEnd: ローカルコマンドの痕跡はターンではない", () => {
  // 入力は新しい順
  const localCmd = [
    user("<local-command-stdout>Set model to `Fable 5` and saved as your default</local-command-stdout>"),
    user("<command-name>/model</command-name>\n            <command-message>model</command-message>"),
    user("<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>"),
  ];

  it("応答完了の後に /effort /model を打っても concluded のまま（実測の 3 レコード形）", () => {
    expect(classifyTurnEnd([...localCmd, duration(), summary(), assistant(), user("x")])).toBe("concluded");
  });

  it("ローカルコマンドだけ（判定材料なし）は unknown。本物のプロンプトが続けば open", () => {
    expect(classifyTurnEnd(localCmd)).toBe("unknown");
    expect(classifyTurnEnd([user("続けて"), ...localCmd, duration(), summary()])).toBe("open");
  });
});

describe("findResumedFromConfirm: transcript による復帰は終端 open のときだけ（turnEnd を渡した場合）", () => {
  const target = (id: string): ConfirmTarget => ({ sessionId: id, projectId: "p1", transcriptPath: `C:/t/${id}.jsonl`, lastEventAt: T0, kind: "idle" });
  const base = { now: () => T0 + CONFIRM_RESUME_MIN_AGE_MS, mtimeMs: () => T0 + CONFIRM_RESUME_MARGIN_MS, registryStatus: () => "idle" };

  it("終端 concluded / unknown（メタ・ローカルコマンドの書き込み）では戻さない。open なら戻す。turnEnd 無しは従来どおり mtime だけ", () => {
    expect(findResumedFromConfirm([target("a")], { ...base, turnEnd: () => "concluded" })).toEqual([]);
    expect(findResumedFromConfirm([target("a")], { ...base, turnEnd: () => "unknown" })).toEqual([]);
    expect(findResumedFromConfirm([target("a")], { ...base, turnEnd: () => "open" })).toMatchObject([{ reason: "transcript" }]);
    expect(findResumedFromConfirm([target("a")], base)).toMatchObject([{ reason: "transcript" }]);
  });

  it("登録簿 busy による復帰は終端に関係なく従来どおり", () => {
    expect(findResumedFromConfirm([target("a")], { ...base, registryStatus: () => "busy", turnEnd: () => "concluded" })).toMatchObject([{ reason: "registry" }]);
  });
});

describe("findIdleConcluded / findDisconnected: 登録簿 idle のまま止まった実行中は「完了」であって「切断」ではない", () => {
  const target = (id: string): SweepTarget => ({ sessionId: id, projectId: "p1", transcriptPath: `C:/t/${id}.jsonl` });

  it("findIdleConcluded: idle かつ TRANSCRIPT_STALE_MS 以上無更新 → 対象。busy / shell / status 無し・保持中・新しい更新は対象外", () => {
    const now = T0 + TRANSCRIPT_STALE_MS;
    const status: Record<string, string | undefined> = { a: "idle", b: "busy", c: "shell", d: undefined, e: "idle", f: "idle" };
    const mtime: Record<string, number> = { a: T0, b: T0, c: T0, d: T0, e: T0 + 1, f: T0 };
    const hits = findIdleConcluded([target("a"), target("b"), target("c"), target("d"), target("e"), target("f")], {
      now: () => now,
      mtimeMs: (p) => mtime[p.slice(5, 6)],
      registryStatus: (sid) => status[sid],
      heldReason: (sid) => (sid === "f" ? "ループ進行中" : undefined),
    });
    expect(hits.map((t) => t.sessionId)).toEqual(["a"]);
  });

  it("findDisconnected: 登録簿 idle は HARD 閾値を超えても切断しない（生きて入力待ち）。status 無しは従来どおり切断", () => {
    const deps = { now: () => T0 + TRANSCRIPT_STALE_HARD_MS + 1, mtimeMs: () => T0, windowPresent: () => false };
    expect(findDisconnected([target("a"), target("b")], { ...deps, registryStatus: (sid) => (sid === "a" ? "idle" : undefined) })).toEqual([target("b")]);
  });
});
